"""Run the downlink window simulator and write results/SIMULATION.md.

    python -m scripts.simulate                       # default: rad750, all methods
    python -m scripts.simulate --adaptation online   # the refitting experiment
    python -m scripts.simulate --all-tiers           # every artifact x every method
    make simulate / make simulate-sweep

Consumes committed artifacts; trains nothing (except the `online` mode, which
refits the loaded model on frames the rover has captured so far -- cheap for
rad750, minutes per refit for the autoencoder tiers).

Outputs:
    runs/sim/<run_id>/windows.jsonl   one record per (method, window)
    runs/sim/<run_id>/summary.json    aggregate metrics for every run
    results/SIMULATION.md             tier x method table
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from dataclasses import asdict
from pathlib import Path

from core import paths
from core.config import ConfigError
from core.logging_utils import get_logger, human_duration, setup_logging
from core.models.registry import load_model, read_artifact_meta
from core.provenance import git_commit
from sim import policy
from sim.mission import DEFAULT_MISSION_SPLITS, build_mission
from sim.window import SimConfig, SimResult, replay, write_windows_jsonl

log = get_logger("novum.simulate")

DEFAULT_TIERS = ("rad750", "myriad", "snapdragon")


def _tier_of(artifact: Path) -> str:
    sidecar = artifact.with_suffix(".json")
    if sidecar.exists():
        try:
            return json.loads(sidecar.read_text(encoding="utf-8")).get("tier") or artifact.stem
        except json.JSONDecodeError:
            pass
    return artifact.stem


def _cycles_per_score(artifact: Path, model) -> tuple[float, float]:
    """(cycles per full novelty score, cycles per flop) from the tier config."""
    sidecar = artifact.with_suffix(".json")
    cycles_per_flop = 3.0
    if sidecar.exists():
        try:
            record = json.loads(sidecar.read_text(encoding="utf-8"))
            budget = record.get("compute_budget") or {}
            if budget.get("cycles_per_inference"):
                return float(budget["cycles_per_inference"]), float(
                    budget.get("cycles_per_flop", cycles_per_flop)
                )
            cycles_per_flop = float(budget.get("cycles_per_flop", cycles_per_flop))
        except json.JSONDecodeError:
            pass
    return float(model.flops_per_inference()) * cycles_per_flop, cycles_per_flop


def run_one(
    artifact: Path,
    mission,
    methods: list[str],
    config: SimConfig,
    out_dir: Path,
) -> list[SimResult]:
    model = load_model(artifact)
    meta = read_artifact_meta(artifact)
    tier = _tier_of(artifact)
    cycles_per_score, cycles_per_flop = _cycles_per_score(artifact, model)
    config.cycles_per_flop = cycles_per_flop

    log.info(
        "%s (%s): %s cycles per novelty score, adaptation=%s",
        tier,
        meta.get("type"),
        f"{cycles_per_score:,.0f}",
        config.adaptation,
    )

    results: list[SimResult] = []
    for method in methods:
        # Each method starts from a pristine model: an online run that refit
        # under one policy must not hand a warm model to the next.
        fresh = load_model(artifact)
        result = replay(
            mission,
            fresh,
            method=method,
            config=config,
            cycles_per_score=cycles_per_score,
            artifact=str(paths.rel(artifact)),
            tier=tier,
        )
        write_windows_jsonl(result, out_dir / "windows" / f"{tier}-{method}.jsonl")
        results.append(result)
        log.info(
            "  %-13s science yield %.3f | wasted bits %.3f | expired %3d | "
            "unscored %4d | sent %3d (%s)",
            method,
            result.science_yield,
            result.wasted_bit_share,
            result.n_expired,
            result.n_unscored,
            result.n_sent,
            human_duration(result.wall_clock_seconds),
        )
    return results


def write_simulation_md(results: list[SimResult], mission, path: Path, config: SimConfig) -> Path:
    by_tier: dict[str, list[SimResult]] = {}
    for result in results:
        by_tier.setdefault(result.tier, []).append(result)

    def tier_key(name: str) -> tuple[int, str]:
        try:
            return (DEFAULT_TIERS.index(name), name)
        except ValueError:
            return (len(DEFAULT_TIERS), name)

    first = results[0]
    derivation = first.config.get("derivation", {})

    lines = [
        "# NOVUM downlink simulation: what actually reaches the ground",
        "",
        f"Generated by `make simulate` on {time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())} "
        f"(commit `{(git_commit() or 'unknown')[:8]}`, seed {config.seed}, "
        f"adaptation `{config.adaptation}`).",
        "",
        "The static evaluation asks whether a frame is unlike the *training set*. "
        "This replays the mission in sol order and asks whether it is unlike what "
        "has been seen **so far** — the question the rover actually faces. Expect "
        "lower numbers than the static tables; that is the honest measurement, not "
        "a regression.",
        "",
        "## The mission",
        "",
        f"- **{len(mission)} frames** over sols {mission.sols.min()}–{mission.sols.max()}, "
        f"from `{' + '.join(mission.splits)}`",
        f"- composition: {mission.n_natural} natural-novel, {mission.n_rover} rover-novel, "
        f"{mission.n_typical} typical",
        f"- **{derivation.get('n_windows', '?')} downlink windows** at "
        f"{config.sols_per_window} sols each, ~"
        f"{derivation.get('frames_per_window_arriving', 0):.1f} frames arriving per window",
        f"- **bit budget**: {config.downlink_fraction:.0%} of what is captured = "
        f"{derivation.get('bits_per_window', 0):,.0f} bits/window ≈ "
        f"{derivation.get('frames_affordable_per_window', 0):.1f} frames",
        f"- **cycle budget**: {derivation.get('cycles_per_window', 0):,.0f} cycles/window ≈ "
        f"{derivation.get('scores_affordable_per_window', 0) or 0:.1f} full novelty scores",
        f"- unselected frames are retained for up to **{config.buffer_max_age_sols} sols**, "
        "then expire unsent",
        "",
        "Budgets are scaled to the arrival rate on purpose. The tier configs allot "
        "8 Mbit per window (162 frames), but only ~27 frames arrive per window here — "
        "an absolute budget would never bind and the simulation would be theatre.",
        "",
        "## Science yield by tier and method",
        "",
        "**Science yield** = of all natural-class novel frames the rover captured, the "
        "fraction that reached the ground. **Wasted bits** = share of the downlink spent "
        "on rover-made classes (drt, dump-pile, drill-hole, scuff).",
        "",
        "| tier | method | science yield | wasted bits | expired unsent | never scored | "
        "frames sent | natural precision |",
        "|---|---|---|---|---|---|---|---|",
    ]

    for tier in sorted(by_tier, key=tier_key):
        for result in by_tier[tier]:
            name = result.method
            if policy.is_oracle(name):
                name = f"*{name}*"
            lines.append(
                f"| {tier} | {name} | **{result.science_yield:.3f}** | "
                f"{result.wasted_bit_share:.3f} | {result.n_expired} | "
                f"{result.n_unscored} | {result.n_sent} | {result.precision_natural:.3f} |"
            )

    # The headline comparison: NOVUM vs FIFO vs the oracle, per tier.
    lines += ["", "## What intelligence buys, at an identical bit budget", ""]
    comparisons = []
    for tier in sorted(by_tier, key=tier_key):
        runs = {r.method: r for r in by_tier[tier]}
        fifo = runs.get("fifo")
        best_method, best = max(
            ((m, r) for m, r in runs.items() if not policy.is_oracle(m)),
            key=lambda kv: kv[1].science_yield,
        )
        oracle = runs.get("oracle")
        if not fifo:
            continue
        gain = best.science_yield - fifo.science_yield
        relative = (gain / fifo.science_yield) if fifo.science_yield else float("inf")
        gap = (oracle.science_yield - best.science_yield) if oracle else None
        comparisons.append(
            f"| {tier} | {fifo.science_yield:.3f} | {best.science_yield:.3f} "
            f"(`{best_method}`) | **{gain:+.3f}** ({relative:+.0%}) | "
            + (f"{oracle.science_yield:.3f} | {gap:.3f} |" if oracle else "- | - |")
        )
    if comparisons:
        lines += [
            "| tier | FIFO | best onboard policy | gain over FIFO | oracle | remaining gap |",
            "|---|---|---|---|---|---|",
            *comparisons,
        ]

    lines += [
        "",
        "`oracle` reads the ground-truth labels and cannot run onboard; it is the "
        "upper bound any selector could reach under the same bit budget. FIFO needs "
        "no novelty score, so it pays no cycle tax — which is precisely why it is "
        "the honest baseline rather than a strawman.",
        "",
        "## Where the compute budget bit",
        "",
        "Scoring costs cycles. When the buffer holds more frames than the cycle "
        "budget can score, the cheap prefilter (per-frame variance + spectral "
        "spread, ~14% of a PCA score) decides what gets looked at properly; "
        "everything else is left unscored and cannot be selected by a score-based "
        "policy. `never scored` above counts those frame-window pairs.",
        "",
        "| tier | method | scores affordable/window | frames left unscored | prefilter recall of natural |",
        "|---|---|---|---|---|",
    ]
    for tier in sorted(by_tier, key=tier_key):
        for result in by_tier[tier]:
            if not policy.needs_scores(result.method):
                continue
            recalls = [w.prefilter_recall for w in result.windows if w.prefilter_recall is not None]
            recall = f"{sum(recalls) / len(recalls):.3f}" if recalls else "n/a (never binding)"
            affordable = result.config.get("derivation", {}).get("scores_affordable_per_window")
            lines.append(
                f"| {tier} | {result.method} | {affordable:.1f} | {result.n_unscored} | {recall} |"
                if affordable
                else f"| {tier} | {result.method} | - | {result.n_unscored} | {recall} |"
            )

    lines += [
        "",
        "Per-window and cumulative curves for every run are in "
        "`runs/sim/<run_id>/windows/<tier>-<method>.jsonl` — one record per window "
        "with the decisions, budgets, binding constraint, and the running science "
        "yield.",
        "",
        "## Caveats worth stating",
        "",
        "- **`frozen` is optimistic.** The pre-launch model was trained on "
        "`train_typical`, which spans the whole mission including sols the rover has "
        "not reached yet. A real pre-launch model could only have been trained on "
        "terrain from before launch. `--adaptation online` is the honest variant: it "
        "bootstraps on the first sols and refits from what it has actually seen.",
        "- **Ground feedback is off.** There is no ground truth onboard. "
        "`--ground-feedback` simulates a low-bandwidth uplink of expert corrections "
        "and is deliberately excluded from these headline numbers.",
        "- The mission is 856 frames of which 430 are novel — a far higher novelty "
        "rate than a real mission, because it is built from a labelled evaluation "
        "set. Yields here are not mission predictions; the comparison *between* "
        "methods at an identical budget is the result.",
    ]

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="python -m scripts.simulate",
        description="Replay the mission under a downlink and a compute budget.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--artifact", type=Path, action="append", default=None,
                   help="artifact to simulate (repeatable; default: artifacts/rad750.npz)")
    p.add_argument("--all-tiers", action="store_true", help="every artifact in artifacts/")
    p.add_argument("--methods", default=",".join(policy.METHODS),
                   help=f"comma-separated selection policies from {policy.METHODS}")
    p.add_argument("--adaptation", default="frozen", choices=("frozen", "online"))
    p.add_argument("--ground-feedback", action="store_true",
                   help="simulate an expert-correction uplink (implies --adaptation online)")
    p.add_argument("--sols-per-window", type=int, default=50)
    p.add_argument("--downlink-fraction", type=float, default=0.25)
    p.add_argument("--compute-fraction", type=float, default=1.0)
    p.add_argument("--buffer-max-age-sols", type=int, default=200)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--splits", default=",".join(DEFAULT_MISSION_SPLITS))
    p.add_argument("--out-dir", type=Path, default=None, help="default: runs/sim/<timestamp>")
    p.add_argument("--results-file", type=Path, default=None,
                   help="default: results/SIMULATION.md")
    p.add_argument("--log-level", default=None)
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    setup_logging(args.log_level, force=args.log_level is not None)

    methods = [m.strip() for m in args.methods.split(",") if m.strip()]
    unknown = set(methods) - set(policy.METHODS)
    if unknown:
        log.error("unknown method(s): %s; expected from %s", sorted(unknown), policy.METHODS)
        return 2

    artifacts: list[Path]
    if args.all_tiers:
        artifacts = sorted(paths.artifacts_dir().glob("*.npz"))
    elif args.artifact:
        artifacts = [Path(a) for a in args.artifact]
    else:
        artifacts = [paths.artifacts_dir() / "rad750.npz"]

    missing = [a for a in artifacts if not a.exists()]
    if missing:
        log.error("no artifact at %s. Train one first: make train", ", ".join(map(str, missing)))
        return 2

    config = SimConfig(
        sols_per_window=args.sols_per_window,
        downlink_fraction=args.downlink_fraction,
        compute_fraction=args.compute_fraction,
        buffer_max_age_sols=args.buffer_max_age_sols,
        adaptation="online" if args.ground_feedback else args.adaptation,
        ground_feedback=args.ground_feedback,
        seed=args.seed,
    )
    try:
        config.validate()
    except ValueError as exc:
        log.error("%s", exc)
        return 2

    started = time.time()
    stamp = time.strftime("%Y%m%d-%H%M%S", time.gmtime(started))
    out_dir = Path(args.out_dir or (paths.runs_dir() / "sim" / stamp))
    out_dir.mkdir(parents=True, exist_ok=True)

    try:
        splits = tuple(s.strip() for s in args.splits.split(",") if s.strip())
        mission = build_mission(splits)
    except (FileNotFoundError, KeyError) as exc:
        log.error("%s. Run `make data` first.", exc)
        return 2

    log.info("=" * 68)
    log.info(
        "mission: %d frames, sols %d-%d, %d natural / %d rover / %d typical",
        len(mission), mission.sols.min(), mission.sols.max(),
        mission.n_natural, mission.n_rover, mission.n_typical,
    )
    log.info("=" * 68)

    results: list[SimResult] = []
    for artifact in artifacts:
        try:
            results.extend(run_one(artifact, mission, methods, config, out_dir))
        except (ValueError, KeyError, ConfigError) as exc:
            log.error("%s failed: %s", artifact.name, exc)
            return 1

    summary = {
        "created_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "git_commit": git_commit(),
        "config": asdict(config),
        "mission": {
            "splits": list(mission.splits),
            "n_frames": len(mission),
            "sol_min": int(mission.sols.min()),
            "sol_max": int(mission.sols.max()),
            "composition": mission.composition(),
        },
        "runs": [r.to_json() for r in results],
    }
    (out_dir / "summary.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")

    results_file = Path(args.results_file or (paths.PROJECT_ROOT / "results" / "SIMULATION.md"))
    write_simulation_md(results, mission, results_file, config)

    print("", flush=True)
    print("=" * 68)
    print(f"  simulation complete in {human_duration(time.time() - started)}")
    print(f"  table   -> {paths.rel(results_file)}")
    print(f"  detail  -> {paths.rel(out_dir)}")
    print("=" * 68)
    for result in results:
        print(
            f"  {result.tier:<12s} {result.method:<13s} "
            f"science yield {result.science_yield:.3f}  wasted {result.wasted_bit_share:.3f}"
        )
    print("", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
